
[build]
  publish = "."
  command = "echo 'Build BTECE réussi'"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Désactiver temporairement le scanning des secrets
[secrets]
  scan_enabled = false