
[build]
  publish = "."
  command = "echo 'Build réussi - Site statique BTECE'"

[build.environment]
  NODE_VERSION = "18"
  # Désactivation complète du scanning des secrets
  SECRETS_SCAN_ENABLED = "false"
  # Désactivation de la détection intelligente des secrets
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"

[dev]
  port = 3000
  publish = "."
  command = "npm run dev"

# Redirection SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Redirection vers la page de confirmation après soumission du formulaire
[[redirects]]
  from = "/confirmation"
  to = "/confirmation.html"
  status = 200

# Redirection pour le traitement du formulaire Netlify
[[redirects]]
  from = "/.netlify/functions/process-form"
  to = "/.netlify/functions/process-form"
  status = 200

# Redirections de sécurité
[[redirects]]
  from = "/.env"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/wp-admin/*"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/.git/*"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/.env.*"
  to = "/404.html"
  status = 404

# Headers de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# Cache pour les assets statiques
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Configuration des fonctions serverless
[functions]
  # Dossier où se trouvent vos fonctions serverless
  directory = "netlify/functions"
  # Temps d'exécution maximum pour les fonctions (en secondes)
  timeout = 10
  # Modules externes à inclure
  external_node_modules = ["nodemailer", "dotenv"]

# Variables d'environnement par contexte
[context.production.environment]
  NODE_ENV = "production"
  SITE_URL = "https://btece.netlify.app/"
  # Configuration Gmail
  GMAIL_USER = "votre-email@gmail.com"
  GMAIL_PASS = "votre-mot-de-passe-app"
  # Clé secrète pour la validation des emails
  EMAIL_SECRET = "votre-secret-email"

[context.deploy-preview.environment]
  NODE_ENV = "development"

[context.branch-deploy.environment]
  NODE_ENV = "development"

# Configuration du traitement des forms Netlify
[forms]
  # Désactivation du scanning automatique des forms
  scanning_enabled = false
  # Nom du form pour les inscriptions
  [forms.custom_fields.inscription]
    required = true
    type = "string"

# Configuration de la fonction d'envoi d'email
[[redirects]]
  from = "/api/send-email"
  to = "/.netlify/functions/send-email"
  status = 200
  force = true

# Redirection pour les erreurs 404
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
  conditions = {Status = 404}

# Optimisation des performances
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Content-Type = "image/webp"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "POST, GET, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"