
[build]
  publish = "."  # Répertoire de build (racine pour un site statique)
  command = "echo 'Build réussi'"  # Commande de build (vide pour site statique)

# Paramètres de build et déploiement
[build.environment]
  NODE_VERSION = "18"  # Version de Node.js

# Redirections et réécritures d'URL
[[redirects]]
  from = "/apropos"
  to = "/about.html"
  status = 301

[[redirects]]
  from = "/services"
  to = "/services.html"
  status = 301

[[redirects]]
  from = "/produits"
  to = "/products.html"
  status = 301

[[redirects]]
  from = "/projets"
  to = "/projects.html"
  status = 301

[[redirects]]
  from = "/blog"
  to = "/blog.html"
  status = 301

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 301

[[redirects]]
  from = "/accueil"
  to = "/index.html"
  status = 301

# Redirection de la racine du domaine nu
[[redirects]]
  from = "https://btece.netlify.app/*"
  to = "https://www.btece.com/:splat"
  status = 301
  force = true

# Gestion des pages 404
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Headers de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    # Protection XSS
    X-XSS-Protection = "1; mode=block"
    # Empêcher le MIME-sniffing
    X-Content-Type-Options = "nosniff"
    # Referrer Policy
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Permissions Policy
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    # Prévention du clickjacking
    X-Frame-Options = "DENY"
    # Feature Policy (pour compatibilité)
    Feature-Policy = "geolocation 'none'; microphone 'none'; camera 'none'"

[[headers]]
  for = "/assets/*"
  [headers.values]
    # Cache les assets statiques pendant 1 an
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    # Headers spécifiques pour les fichiers JavaScript
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    # Headers spécifiques pour les fichiers CSS
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.html"
  [headers.values]
    # Pas de cache pour les pages HTML
    Cache-Control = "public, max-age=0, must-revalidate"

# Paramètres de fonctionnalités Netlify
[functions]
  # Répertoire des fonctions serverless
  directory = "functions/"

# Intégrations
[context.production.environment]
  # Variables d'environnement pour la production
  EMAILJS_SERVICE_ID = "service_abc123"
  EMAILJS_TEMPLATE_ID = "template_xyz789"
  EMAILJS_PUBLIC_KEY = "user_abcdefghijk123456"

[context.deploy-preview.environment]
  # Variables pour les previews de déploiement
  NODE_ENV = "development"

[context.branch-deploy.environment]
  # Variables pour les déploiements de branches
  NODE_ENV = "development"

# Paramètres de traitement des formulaires
[forms]
  # Détection automatique des formulaires
  honey-pot = "hp_"
  # Détection de spam
  spam-filter = true

# Paramètres de sécurité avancés
[security]
  [security.http]
    # Strict Transport Security
    [security.http.strict_transport_security]
      enable = true
      max_age = 31536000
      include_subdomains = true
      preload = true

# Paramètres de compression
[compression]
  # Compression Gzip et Brotli
  gzip = true
  brotli = true

# Paramètres de build optimisé
[build.processing]
  # Optimisation des images
  image_optimization = true
  # Minification HTML
  html = true
  # Minification CSS
  css = true
  # Minification JS
  js = true
  # Minification des assets
  skip_processing = false

# Configuration pour les prerenderings
[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Paramètres de performances
[build.processing.images]
  optimize = true
  compress = true

# Paramètres de surveillance
[build.observability]
  # Activation des métriques de performance
  enabled = true

# Configuration pour les environnements spécifiques
[context.production]
  command = "echo 'Build de production'"

[context.deploy-preview]
  command = "echo 'Build de prévisualisation'"
  publish = "/"

[context.branch-deploy]
  command = "echo 'Build de branche'"
  publish = "/"