[build]
  # Pas de commande de build nécessaire (fichiers statiques)
  command = "echo 'Build skipped - static site'"
  
  # Netlify doit déployer les fichiers à la racine
  publish = "."

# Paramètres de déploiement
[build.environment]
  NODE_VERSION = "18"  # Maintient la compatibilité si vous ajoutez des fonctions
  PHP_VERSION = "8.2"  # Pré-installe PHP au cas où

# Redirections intelligentes (supprime les .html des URLs)
[[redirects]]
  from = "/a-propos"
  to = "/about.html"
  status = 200
  force = true

[[redirects]]
  from = "/services"
  to = "/services.html"
  status = 200
  force = true

[[redirects]]
  from = "/projets"
  to = "/projects.html"
  status = 200
  force = true

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200
  force = true

# Gestion des erreurs
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Optimisation des en-têtes HTTP
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

# Sécurité renforcée
[[headers]]
  for = "/*"
  [headers.values]
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# Préchargement des assets critiques (optionnel)
[[headers]]
  for = "/index.html"
  [headers.values]
    Link = '</assets/css/style.css>; rel=preload; as=style, </assets/js/main.js>; rel=preload; as=script'