
[build]
  publish = "."
  command = "echo 'Build réussi - Site statique BTECE'"

[build.environment]
  NODE_VERSION = "18"
  # Désactivation complète du scanning des secrets
  SECRETS_SCAN_ENABLED = "false"
  # Désactivation de la détection intelligente des secrets
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"

[dev]
  port = 3000
  publish = "."

# Configuration des fonctions serverless
[functions]
  # Dossier où se trouvent vos fonctions serverless
  directory = "netlify/functions"
  # Temps d'exécution maximum pour les fonctions (en secondes)
  node_bundler = "esbuild"
  
  # Configuration du timeout (syntaxe corrigée)
  [functions.settings]
    timeout = 10  # Timeout en secondes pour les fonctions synchrones 

  # Modules externes à inclure
  external_node_modules = ["nodemailer", "dotenv", "axios"]

# Redirection SPA (Single Page Application) - Correction du routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Redirections spécifiques pour le dossier formation_professionnelle
[[redirects]]
  from = "/formation_professionnelle/inscription"
  to = "/formation_professionnelle/inscription.html"
  status = 200
  force = true

[[redirects]]
  from = "/formation_professionnelle/confirmation"
  to = "/formation_professionnelle/confirmation.html"
  status = 200
  force = true

[[redirects]]
  from = "/formation_professionnelle/merci"
  to = "/formation_professionnelle/confirmation.html"
  status = 200
  force = true

# Redirection pour le traitement du formulaire Netlify
[[redirects]]
  from = "/.netlify/functions/submit-form"
  to = "/.netlify/functions/submit-form"
  status = 200

# Redirection pour l'envoi d'email
[[redirects]]
  from = "/api/send-email"
  to = "/.netlify/functions/send-email"
  status = 200
  force = true

# Redirection de fallback pour SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Redirections de sécurité
[[redirects]]
  from = "/.env"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/wp-admin/*"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/.git/*"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/.env.*"
  to = "/404.html"
  status = 404

# Headers de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Cache pour les assets statiques
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Headers spécifiques pour les fonctions API
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "POST, GET, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Variables d'environnement par contexte
[context.production.environment]
  NODE_ENV = "production"
  SITE_URL = "https://btece.netlify.app/"
  # Configuration Gmail
  GMAIL_USER = "votre-email@gmail.com"
  GMAIL_PASS = "votre-mot-de-passe-app"
  # Clé secrète pour la validation
  FORM_SECRET = "votre-secret-formulaire"
  # Configuration spécifique pour Netlify Forms
  NETLIFY_FORMS_HANDLER = "true"
  # Chemin vers le dossier formation_professionnelle
  FORMATION_PATH = "/formation_professionnelle"
  # Désactivation des pretty URLs
  PRETTY_URLS = "false"

[context.deploy-preview.environment]
  NODE_ENV = "development"
  PRETTY_URLS = "false"

[context.branch-deploy.environment]
  NODE_ENV = "development"
  PRETTY_URLS = "false"

# Configuration du traitement des forms Netlify
[forms]
  # Désactivation du scanning automatique des forms
  scanning_enabled = false

# Redirection pour les erreurs 404
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
  conditions = {Status = 404}

# Optimisation des performances
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Configuration spécifique pour le traitement des formulaires
# Empêcher la redirection automatique de Netlify Forms
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
  force = true

# Redirections pour les assets dans le dossier formation_professionnelle
[[redirects]]
  from = "/formation_professionnelle/assets/*"
  to = "/formation_professionnelle/assets/:splat"
  status = 200

[[redirects]]
  from = "/formation_professionnelle/*.css"
  to = "/formation_professionnelle/:splat.css"
  status = 200

[[redirects]]
  from = "/formation_professionnelle/*.js"
  to = "/formation_professionnelle/:splat.js"
  status = 200

# Redirection pour le formulaire d'inscription
[[redirects]]
  from = "/inscription"
  to = "/formation_professionnelle/inscription.html"
  status = 200
  force = true

# Redirection pour la page de confirmation
[[redirects]]
  from = "/confirmation"
  to = "/formation_professionnelle/confirmation.html"
  status = 200
  force = true